config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/news',      to: 'static_pages#news'

	get '/signup',    to: 'shepherds#new'

	get '/login',     to: 'sessions#new'
	post '/login',    to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

  get 'password_resets/new'
  get 'password_resets/edit'

	resources :shepherds do
		member do
			get :following, :followers
		end
	end
	get '/:id', to: 'shepherds#show'

	resources :shepherds
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :relationships,       only: [:create, :destroy]

	resources :animals do
		resources :weights, shallow:true, only: [:new, :create, :edit, :update, :destroy]
	end

  get '/shepherds/:username/:eartag', to: 'animals#show', as: :shepherd_animal

end

app/views/shared/_animal_form.html.erb
<% unless !current_shepherd?(@shepherd) %>
	<%= form_for(@new_animal, html: { multipart: true }) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="field">
			<%= f.label :eartag %>
			<%= f.text_field :eartag, class: 'form-control'  %>

			<%= f.label :birth_date %>
			<%= f.text_field :birth_date, class: 'form-control', value: Date.current  %>

			<%= f.label :sex %>
			<%= f.select(:sex, options_for_select([['Unknown', 'unknown'], ['Ewe', 'ewe'], ['Wether','wether'], ['Ram', 'ram'], ['Teaser', 'teaser']], 1)) %>

			<div class="form-group row">
				<div class="col-8" style="padding-right:0;">
					<%= f.label :dam_eartag %>
					<%= f.text_field :dam_eartag, class: 'form-control dam-eartag'  %>
				</div>
				<div class="col-4 mt-auto pb-3" style="padding-left:5px;">
					<%= f.check_box :orphan, :data => {:checked => "checked", :toggle => "toggle", :on => "Orphan", :off=>"Raised", onstyle: "danger", offstyle: "success", height: "36px", width: "100%"}, class: '' %>
				</div>
			</div>

			<%= f.label :sire_eartag %>
			<%= f.text_field :sire_eartag, class: 'form-control'  %>

			<%= f.label :picture %>
			<%= f.file_field :picture, size: 10, accept: 'image/jpeg,image/gif,image/png' %>



		</div>
		<%= f.submit yield(:button_text), class: "btn btn-primary" %>

	<% end %>
<% end %>

app/views/shared/_basic_info.html.erb
<div class="row no-gutters">
	<div class="col-md-4 vcenter">
		<% if animal.picture? %>
			<%= image_tag animal.picture.thumb.url %>
		<% else %>
			<div class="tag_img"><%= animal.eartag %></div>
		<% end %>
	</div><!--
--><div class="col-md-4 vcenter">
		<ul class="description">
			<li><span id="label">Eartag:</span> <span id="eartag"><%= animal.eartag %></span></li>
			<li><span id="label">Sex:</span> <span id="sex"><%= animal.sex.capitalize %></span></li>
			<li><span id="label">Dam:</span> <span id="dam"><%= animal.pedigree[:dam] %></span></li>
			<li><span id="label">Sire:</span> <span id="sire"><%= animal.pedigree[:sire] %></span></li>
			<li><span id="label">Breed:</span> <span id="breed">NA</span></li>
		</ul>
	</div><!--
--><div class="col-md-4 vcenter">
		<ul class="description">
			<li><span id="label">Born:</span> <span id="born"><%= animal.birth_date %> </li>
			<li><span id="label">Raised as:</span> <span id="raised_as"><%= animal.raised_as %></li>
			<li><span id="label">Birth type:</span> <span id="birth_type"><%= animal.birth_type %></li>
			<li><span id="label">Progeny:</span> <span id="progeny">
				<%= animal.n_progeny %> / <%= animal.n_weaned  %> / <%= animal.n_lambings %>
			</li>
			<li><span id="label">Last weight:</span> <span id="last_weight"><%= animal.last_weight %></span></li>
		</ul>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_shepherd_info.html.erb
<%= link_to gravatar_for(@shepherd, size: 50), @shepherd %>
<h1><%= link_to @shepherd.name, @shepherd  %></h1>
<span><%= pluralize(@shepherd.animals.count, "sheep") %></span>
<span>Updated <%= time_ago_in_words(@shepherd.updated_at) %> ago</span>

app/views/shared/_stats.html.erb
<% @shepherd ||= current_shepherd %>
<div class="stats">
	<a href="<%= following_shepherd_path(@shepherd) %>">
		<strong id="following" class="stat">
			<%= @shepherd.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_shepherd_path(@shepherd) %>">
		<strong id="followers" class="stat">
			<%= @shepherd.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_weight_form.html.erb
<% unless !current_shepherd?(@shepherd) %>
	<%
	if @weight.id.nil?
	  args = [@animal, @weight]
		provide(:weight_button_text, "Create new weight")
	else
	  args =  @weight
		provide(:weight_button_text, "Update weight")
	end
	%>

	<%= form_for(args, html: { multipart: true }) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="field">
			<%= f.label :date %>
			<%= f.text_field :date, class: 'form-control', value: @weight.date || Date.current  %>

			<%= f.label :weight %>
			<%= f.text_field :weight, class: 'form-control', value: @weight.weight || nil  %>

			<%= f.label :weight_type %>
			<%= f.select(:weight_type, options_for_select([['Birth', 'birth'], ['Weaning', 'weaning'], ['Early Post Weaning', 'early_post_weaning'], ['Post Weaning', 'post_weaning'], ['Yearling', 'yearling'], ['Hogget', 'hogget'], ['Adult', 'adult'], ['Maintenance', 'maintenance'], ['Hanging', 'hanging']], @weight.weight_type || 1 )) %>
		</div>
		<%= f.submit yield(:weight_button_text), class: "btn btn-primary" %>

		<% if !@weight.id.nil? %>
			<%= link_to "Delete weight", weight_path(@weight.id), method: :delete, data: { confirm: "Are you sure you want to remove this weight record." }, class: "btn btn-primary delete" %>
		<% end %>

		<% if !@weight.id.nil? %>
			<%= link_to "Cancel update", shepherd_animal_path(@shepherd.username, @animal.eartag), class: "btn btn-primary cancel" %>
		<% end %>

	<% end %>
<% end %>