config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/news',      to: 'static_pages#news'

	get '/signup',    to: 'shepherds#new'

	get '/login',     to: 'sessions#new'
	post '/login',    to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

  get 'password_resets/new'
  get 'password_resets/edit'

	resources :shepherds do
		member do
			get :following, :followers
		end
	end
	get '/:id', to: 'shepherds#show'

	resources :shepherds
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :relationships,       only: [:create, :destroy]

	resources :animals do
		resources :weights, shallow:true, only: [:new, :create, :edit, :update, :destroy]
	end

  get '/shepherds/:username/:eartag', to: 'animals#show', as: :shepherd_animal

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Yowbook by <a href="https://github.com/pschloss/">Pat Schloss</a>
  </small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", news_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="header">
	<div class="container">

		<nav class="navbar navbar-expand-sm navbar-dark bg-dark">

			<%= link_to "Yowbook", root_path, id: "logo", class: "navbar-brand" %>

		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>


		  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
		    <ul class="navbar-nav">
					<li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Help", help_path, class: "nav-link"  %></li>

					<% if logged_in? %>
						<li class="nav-item"><%= link_to "Shepherds", shepherds_path, class: "nav-link" %></li>
						<li class="nav-item dropdown">
		        	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Account
							</a>
		        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<li class="dropdown-item"><%= link_to "Profile", current_shepherd %></li>
							<li class="dropdown-item"><%= link_to "Settings", edit_shepherd_path(current_shepherd) %></li>
							<li class="dropdown-divider"></li>
							<li class="dropdown-item"><%= link_to "Log out", logout_path, method: "delete" %></li>
						</ul>
					<% else %>
						<li class="dropdown-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
					<% end %>
				</ul>
			</nav>
		</nav>
	</div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
																							'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
		<%= render 'layouts/rails_default' %>
		<%= render 'layouts/shim' %>
	</head>
  <body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
				<div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>
    	<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
  </body>
</html>